/*
 * Aulas professor Maromo.
 */
package prjjogo;

import java.awt.Component;
import java.awt.HeadlessException;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author maromo
 */
public class FrmJogoVeia extends javax.swing.JFrame {

    //Atributo
    public int vez = 0;

    public void jogar(java.awt.event.ActionEvent evt) {
        JButton btJog = (JButton) evt.getSource();
        if (!btJog.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Casa já jogada");
            return;
        }
        vez++;
        if (vez % 2 == 0) {
            btJog.setText("X");
        } else {
            btJog.setText("0");
        }
        if (verificarGanhador()) return;

    }

    private boolean verificarGanhador() throws HeadlessException {
        //Verificar se há vencedor
        //Ver se "X" ganhou
        if (bt1.getText().equals("X") && bt2.getText().equals("X") && bt3.getText().equals("X")) {
            JOptionPane.showMessageDialog(null, "Jogador X Ganhou");
            return true;
        }
        if (bt4.getText().equals("X") && bt5.getText().equals("X") && bt6.getText().equals("X")) {
            JOptionPane.showMessageDialog(null, "Jogador X Ganhou");
            return true;
        }
        if (bt7.getText().equals("X") && bt8.getText().equals("X") && bt9.getText().equals("X")) {
            JOptionPane.showMessageDialog(null, "Jogador X Ganhou");
            return true;
        }
        if (bt1.getText().equals("X") && bt5.getText().equals("X") && bt9.getText().equals("X")) {
            JOptionPane.showMessageDialog(null, "Jogador X Ganhou");
            return true;
        }
        if (bt3.getText().equals("X") && bt5.getText().equals("X") && bt7.getText().equals("X")) {
            JOptionPane.showMessageDialog(null, "Jogador X Ganhou");
            return true;
        }
        if (bt1.getText().equals("X") && bt4.getText().equals("X") && bt7.getText().equals("X")) {
            JOptionPane.showMessageDialog(null, "Jogador X Ganhou");
            return true;
        }
        if (bt2.getText().equals("X") && bt5.getText().equals("X") && bt8.getText().equals("X")) {
            JOptionPane.showMessageDialog(null, "Jogador X Ganhou");
            return true;
        }
        if (bt3.getText().equals("X") && bt6.getText().equals("X") && bt9.getText().equals("X")) {
            JOptionPane.showMessageDialog(null, "Jogador X Ganhou");
            return true;
        }
        //Ver se "0" ganhou
        if (bt1.getText().equals("0") && bt2.getText().equals("0") && bt3.getText().equals("0")) {
            JOptionPane.showMessageDialog(null, "Jogador 0 Ganhou");
            return true;
        }
        if (bt4.getText().equals("0") && bt5.getText().equals("0") && bt6.getText().equals("0")) {
            JOptionPane.showMessageDialog(null, "Jogador 0 Ganhou");
            return true;
        }
        if (bt7.getText().equals("0") && bt8.getText().equals("0") && bt9.getText().equals("0")) {
            JOptionPane.showMessageDialog(null, "Jogador 0 Ganhou");
            return true;
        }
        if (bt1.getText().equals("0") && bt5.getText().equals("0") && bt9.getText().equals("0")) {
            JOptionPane.showMessageDialog(null, "Jogador 0 Ganhou");
            return true;
        }
        if (bt3.getText().equals("0") && bt5.getText().equals("0") && bt7.getText().equals("0")) {
            JOptionPane.showMessageDialog(null, "Jogador 0 Ganhou");
            return true;
        }
        if (bt1.getText().equals("0") && bt4.getText().equals("0") && bt7.getText().equals("0")) {
            JOptionPane.showMessageDialog(null, "Jogador 0 Ganhou");
            return true;
        }
        if (bt2.getText().equals("0") && bt5.getText().equals("0") && bt8.getText().equals("0")) {
            JOptionPane.showMessageDialog(null, "Jogador 0 Ganhou");
            return true;
        }
        if (bt3.getText().equals("0") && bt6.getText().equals("0") && bt9.getText().equals("0")) {
            JOptionPane.showMessageDialog(null, "Jogador 0 Ganhou");
            return true;
        }
        if (vez == 9) {
            JOptionPane.showMessageDialog(null, "Deu Véia");

        }
        return false;
    }

    /**
     * Creates new form FrmJogoVeia
     */
    public FrmJogoVeia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt1 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        bt5 = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();
        bt6 = new javax.swing.JButton();
        bt8 = new javax.swing.JButton();
        bt7 = new javax.swing.JButton();
        bt9 = new javax.swing.JButton();
        btNovo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });
        getContentPane().add(bt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 90, 90));

        bt2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });
        getContentPane().add(bt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 90, 90));

        bt3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });
        getContentPane().add(bt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 90, 90));

        bt5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt5ActionPerformed(evt);
            }
        });
        getContentPane().add(bt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 90, 90));

        bt4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt4ActionPerformed(evt);
            }
        });
        getContentPane().add(bt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 90, 90));

        bt6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt6ActionPerformed(evt);
            }
        });
        getContentPane().add(bt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 90, 90));

        bt8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt8ActionPerformed(evt);
            }
        });
        getContentPane().add(bt8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 90, 90));

        bt7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt7ActionPerformed(evt);
            }
        });
        getContentPane().add(bt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 90, 90));

        bt9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt9ActionPerformed(evt);
            }
        });
        getContentPane().add(bt9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 90, 90));

        btNovo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btNovo.setText("Novo Jogo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });
        getContentPane().add(btNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 330, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        // TODO add your handling code here:
        //Rotina que limpe o texto de todos os botões
        this.vez = 0;
        for (Component item : this.getContentPane().getComponents()) {
            if (item instanceof JButton) {
                JButton bt = (JButton) item;
                if (!bt.getText().equals("Novo Jogo")) {
                    bt.setText("");
                }
            }
        }
    }//GEN-LAST:event_btNovoActionPerformed

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        // TODO add your handling code here:
        jogar(evt);
    }//GEN-LAST:event_bt1ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        // TODO add your handling code here:
        jogar(evt);
    }//GEN-LAST:event_bt2ActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        // TODO add your handling code here:
        jogar(evt);
    }//GEN-LAST:event_bt3ActionPerformed

    private void bt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt4ActionPerformed
        // TODO add your handling code here:
        jogar(evt);
    }//GEN-LAST:event_bt4ActionPerformed

    private void bt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt5ActionPerformed
        // TODO add your handling code here:
        jogar(evt);
    }//GEN-LAST:event_bt5ActionPerformed

    private void bt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt6ActionPerformed
        // TODO add your handling code here:
        jogar(evt);
    }//GEN-LAST:event_bt6ActionPerformed

    private void bt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt7ActionPerformed
        // TODO add your handling code here:
        jogar(evt);
    }//GEN-LAST:event_bt7ActionPerformed

    private void bt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt8ActionPerformed
        // TODO add your handling code here:
        jogar(evt);
    }//GEN-LAST:event_bt8ActionPerformed

    private void bt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt9ActionPerformed
        // TODO add your handling code here:
        jogar(evt);
    }//GEN-LAST:event_bt9ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JButton bt5;
    private javax.swing.JButton bt6;
    private javax.swing.JButton bt7;
    private javax.swing.JButton bt8;
    private javax.swing.JButton bt9;
    private javax.swing.JButton btNovo;
    // End of variables declaration//GEN-END:variables
}
